// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface MenuItems {
  data: Datum[];
}

export interface Datum {
  name: string;
  url?: string;
  children?: DatumChild[];
}

export interface DatumChild {
  name: string;
  url?: string;
  children?: ChildChild[];
}

export interface ChildChild {
  name: string;
  url: string;
}
